.\" Copyright (c) 2018 Yon <anaseto@bardinflor.perso.aquilenet.fr>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.Dd Nov 28, 2018
.Dt BOOHU 6
.Os
.Sh NAME
.Nm boohu
.Nd coffee-break roguelike game
.Sh SYNOPSIS
.Nm
.Op Fl c
.Op Fl n
.Op Fl o
.Op Fl s
.Op Fl v
.Op Fl x
.Op Fl r Ar file
.Sh DESCRIPTION
Break Out Of Hareka's Underground (Boohu) is a turn-based coffee-break
roguelike game with a heavy focus on tactical positioning mechanisms.
This focus strongly influenced its weapon attack patterns, consumables and
terrain features.
Aiming for a replayable streamlined experience, the game avoids manual
inventory management and complex character building, relying on items and
player adaptability for character progression.
.Pp
“Every year, the elders send someone to collect medicinal simella plants in the
Underground.
This year, the honor fell upon you, and so here you are.
According to the elders, deep in the Underground, a magical monolith will lead you
back to your village.”
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl c
Use a centered camera.
.It Fl n
No animations.
.It Fl o
Use 8-color palette.
.It Fl r Ar file
Watch replay file
.Ar file
instead of launching a normal game.
If
.Ar file
is
.Sq _ ,
the last game replay is used.
The following key bindings are available:
.Cm +
and
.Cm -
for changing speed,
the arrow keys for going to next or previous frame,
.Cm space
and
.Cm p
for pausing/resuming the video,
and
.Cm Q
for exiting the program.
.It Fl s
Use the 16-color solarized palette.
.It Fl v
Print version number.
.It Fl x
Use xterm 256-color palette (solarized approximation). This is the default.
.El
.Sh FILES
.Bl -tag -width Ds -compact
.It Pa "$XDG_DATA_HOME/boohu/save"
Last saved game.
.It Pa "$XDG_DATA_HOME/boohu/dump"
Last game character and statistics.
.It Pa "$XDG_DATA_HOME/boohu/config.gob"
Key bindings configuration.
.It Pa "$XDG_DATA_HOME/boohu/replay"
Last game replay file.
.El
