.\" Copyright (c) 2018 Yon <anaseto@bardinflor.perso.aquilenet.fr>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.Dd Apr 28, 2019
.Dt HARMONIST 6
.Os
.Sh NAME
.Nm harmonist
.Nd stealth roguelike game
.Sh SYNOPSIS
.Nm
.Op Fl c
.Op Fl n
.Op Fl o
.Op Fl s
.Op Fl v
.Op Fl x
.Op Fl r Ar file
.Sh DESCRIPTION
Harmonist is a stealth coffee-break roguelike game.
The game has a heavy focus on tactical positioning, light and noise mechanisms,
making use of various terrain types and cones of view for monsters.
Aiming for a replayable streamlined experience, the game avoids complex
inventory management and character building, relying on items and player
adaptability for character progression.
.Pp
“Your friend Shaedra got captured by nasty people from the Dayoriah Clan while
she was trying to retrieve a powerful magara artifact that was stolen from the
great magara-specialist Marevor Helith.
As a gawalt monkey, you don't understand much why people complicate so much
their lives caring about artifacts and the like, but one thing is clear: you
have to rescue your friend, somewhere to be found in this Underground area
controlled by the Dayoriah Clan.
If what you heard the guards say is true, Shaedra's imprisoned on the eighth
floor.
You are small and have good night vision, so you hope the infiltration
will go smoothly...”
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl c
Use a centered camera.
.It Fl n
No animations.
.It Fl o
Use 8-color palette.
.It Fl r Ar file
Watch replay file
.Ar file
instead of launching a normal game.
If
.Ar file
is
.Sq _ ,
the last game replay is used.
The following key bindings are available:
.Cm +
and
.Cm -
for changing speed,
the arrow keys for going to next or previous frame,
.Cm space
and
.Cm p
for pausing/resuming the video,
and
.Cm Q
for exiting the program.
.It Fl s
Use the 16-color solarized palette.
.It Fl v
Print version number.
.It Fl x
Use xterm 256-color palette (solarized approximation). This is the default.
.El
.Sh FILES
.Bl -tag -width Ds -compact
.It Pa "$XDG_DATA_HOME/harmonist/save"
Last saved game.
.It Pa "$XDG_DATA_HOME/harmonist/dump"
Last game character and statistics.
.It Pa "$XDG_DATA_HOME/harmonist/config.gob"
Key bindings configuration.
.It Pa "$XDG_DATA_HOME/harmonist/replay"
Last game replay file.
.El
